### ISSUE TITLE
Using extracted Windows key after flashing 1vyrain

### ISSUE THREAD

**Issue by rnsc5jjjjj** [n4ru/1vyrain#122]
There are many notes telling how to get the Windows license key from a running Windows machine, an image of a dead Windows machine, and even from a Linux machine.  I have done this.

Posts to "T430s lost windows 7 license after this procedure #63" seem to take for granted that with this key one can activate Windows and that it will work just as well as if it were in the BIOS.  But after flashing 1vyrain it will not BE in the BIOS.  

None of the posts state that this is known to work.  I can imagine Microsoft knowing that this is a Lenovo key, checking the BIOS, seeing that it is not there, and refusing to use it.  

Can anyone vouch for this actually working?  By this I mean that I simply need to type it in, just like we used to do when there were stickers, and only on a clean install.  I don't want to lose my Windows licenses!

I recently upgraded a T530 and T430 to quad-core i7-3632s and they need a little help in the cooling department under heavy load, especially the T430.  Neither running the fan very fast at all.

And thank you for this wonderful tool to enable me to put sensible fan curves in place (Among other things!).

Thank you!

--Ray

**Comment by digmorepaka** [comment]
> None of the posts state that this is known to work. I can imagine Microsoft knowing that this is a Lenovo key, checking the BIOS, seeing that it is not there, and refusing to use it.

It does work. Also no such check is conducted, not on Windows 7, nor on Windows 10. Well, you can't activate 10 with a 7 key anymore because Microsoft wanted to kill hwidgen. But when it was a thing it didn't check it. You could actually activate a completely different computer with an OEM key both on 10 and 7. This is also how the grey key market works. OEM buys thousands of keys for cents, and an employee takes a couple hundred and puts them up on these marketplaces.
