### ISSUE TITLE
Lenovo L430 is Compatible

### ISSUE THREAD

**Issue by dte102** [n4ru/1vyrain#27]
Decided to try out the patch on an L430 thinkpad, and the result that it's compatible.

Machine: L430
Bios: G3ET94WW(2.54)
Version:
Flashsize: 80 M

**Comment by n4ru** [comment]
Great to hear!

Flashsize seems incorrect though. You sure it's 80 and not 8?

**Comment by dte102** [comment]
Yeah, ran it again to make sure and got a flash size of 80 M.  Gonna attach a picture of the result just in case I'm misinterpreting something though
![IMG_20200227_191924](https://user-images.githubusercontent.com/17890758/75504731-8637ed00-5996-11ea-9ce4-7f0e3fe2495e.jpg)
.

**Comment by n4ru** [comment]
Interesting. I'll take a look, maybe I messed up with printing it.

Your laptop is def compatible though so I'll take a deeper look.

**Comment by dte102** [comment]
Good to know!
If you need the laptop for any reason, I'll be happy to ship this one over if needed.

**Comment by digmorepaka** [comment]
@dte102 It would be highly appreciated if you ran `flashrom -p internal:laptop=force_I_want_a_brick --ifd -i fd -r L430_ifd.rom` and uploaded the `L430_ifd.rom` somewhere. You should be able to run this from a regular linux install with the `iomem=relaxed` kernel option, or the 1vyrain usb. :D

**Comment by dte102** [comment]
Here's a zip of the rom file I got from running the command on the L430.
[L430_ifd.rom.zip](https://github.com/n4ru/1vyrain/files/4266815/L430_ifd.rom.zip)

**Comment by digmorepaka** [comment]
@dte102 wonderful, Thank you!

**Comment by n4ru** [comment]
Looked into the BIOS patches, and unfortunately none of them seem compatible with the L430, either the new BIOS or the older revisions. It is 100% doable for sure, but unfortunately the existing patches that we have seem to only work on the main line of ThinkPad products (T/X/W). I don't foresee having time to explore new patches by myself, so I apologize in advance; but if we find a better way to generate patches or eventually come back around to this, I will let you know.

**Comment by dte102** [comment]
Gotcha, that's fine since we know that it's at least compatible and that at some point the L430 might get support.  Thanks for looking into it!

**Comment by n4ru** [comment]
Took another look at this, and turns out I was wrong and that the patches _are_ compatible. My error was that the offset for where the 4MB BIOS begins is different. You can create a fully customizable BIOS for your L430.

You can extract your BIOS from the FL1 file with `dd if=01D4000.FL1 bs=1 of=4MB skip=4325840 count=4194304`, then patch it with UEFIPatch using [this documentation](https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654#dbff) for all the _non whitelist patches_.

For whitelist patches, the L430 has slightly different offsets. Add these patches in addition to whichever other ones you want:

```
79E0EDD7-9D1D-4F41-AE1A-F896169E5216 10 P:C8390E0F84:C8390E90E9 
79E0EDD7-9D1D-4F41-AE1A-F896169E5216 10 P:C8390E75620F:C8390E75000F 
79E0EDD7-9D1D-4F41-AE1A-F896169E5216 10 P:0983FA0474:0983FA04EB 
```

Once you've created your custom BIOS, just run 1vyrain to unlock your BIOS region, then flash your file with flashrom.

**Comment by unrelentingtech** [comment]
(See #87 for further L430 discussion)

In addition to the patches above, one more is required:

```
79E0EDD7-9D1D-4F41-AE1A-F896169E5216 10 P:C8394E04754E83:C8394E04750083
```

because there's one more condition right after `C8390E75620F`
