### ISSUE TITLE
Questions about 1vyrain

### ISSUE THREAD

**Issue by samveen** [n4ru/1vyrain#31]
_Caveat Emptor: I have an x230 and everything mentioned here is based on it, but hopefully is easy to generalize_

I am trying to create reproducible builds for the bios files in the patched-bios submodule of 1vyrain (the n4ru/patched-bioses repo), but I was unsure of the base bios version is used to create those files.

 I followed the steps for [self-building 1vyrain](https://medium.com/@n4ru/1vyrain-self-build-documentation-5059825b1fdb), but there isn't any information on what is the base of the patched-bios files in it. Due to a still-unexplained mix-up in my reading list's order ([1vyrain](https://github.com/n4ru/1vyrain) + [heads](https://github.com/osresearch/heads) + [skulls](https://github.com/merge/skulls) + [thinkpad-ec](https://github.com/hamishcoleman/thinkpad-ec) + [thinkpad bios flashing guide](https://github.com/gch1p/thinkpad-bios-software-flashing-guide)), I ended up building a patched x230 bios rom based on  `BIOS 2.75 (G2ETB5WW) + EC 1.14 (G2HT35WW)` (`//:/FLASH/G2ETB5WW/$01D3000.FL1` from `g2uj31us.iso`) . As expected, the generated file and the files from `patched-bios` did not match, and so I didn't try creating a brick.

A more detailed read of the [longer form FAQ](https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654]) told me that the patches listed in it are for the bios version released **after** _September 2019_. The [current bios release file](https://download.lenovo.com/pccbbs/mobiles/g2uj33us.txt) lists that as BIOS 2.77  (G2ETB7WW) + EC 1.15  (G2HT36WW) released 2019/10/03. 

Armed with this info, I tried the same process as earlier, but on the bios file from 2.77 (G2ETB7WW), and the generated file actually matches exactly: 

```
samveen@X230: ~/builds/x230 $ diff x230.G2ETB7WW.s01D3000.patched.rom ../../patched-bios/X230.rom 
```
This brings up some questions I have about 1vyrain:
 - ~~In case the next bios version is released (probably 2.78?), will the process of upgrade be to downgrade back to BIOS 2.60 and then apply a patched bios again? As I understand the patches, there's nothing in there to introduce vulnerabilities into the bios that make 1vyrain possible (and they shouldn't, right?).~~ Already answered by #10 and #26 .
- I'm trying to create a travis-ci config such that the patched bios roms can be auto-generated and added as release artifacts to the 1vyrain repository (automated builds as well as open and auditible process). Would you be open to review that if I submit a pull request?

**Comment by n4ru** [comment]
I did some minor investigating recently, but after several bricks, gave up on building an "unlock" patch for the 1vyrain patched-bioses. Because IFD actually leaves BIOS unlocked and the Lenovo BIOS locks itself from writing on boot, it should theoretically be possible to remove the lock as a patch itself and be able to update without downgrading past the first time.

Unfortunately, I don't have time or energy to continue restoring bricks after failed attempts, and because of the ease of downgrading with IVPrep or even a normal USB drive method (for Linux users), I'm done messing around with that for the time being. When a new BIOS is released (which will likely only occur after major vulns, since "feature" updates are long since done), you'll just have to downgrade and then run 1vyrain with the newest pre-patched BIOS or your own. Because of the lack of consistent BIOS updates, this is more of a nice to have and a personal curiosity than a major TODO.

I'm not familiar enough with travis-ci, but what you're asking for should be possible and I'll happily merge a completed solution.

As far as your patched BIOS goes, you should be able to easily reproduce exact copies of the BIOSes in the patched-bios repository by applying patches to the latest BIOS releases. I don't have the time to handhold, but if you have specific questions and a grasp of the basic process I can try to lead you in the right direction. As of this comment, the latest version of all supported BIOSes was used to create the patched BIOS files.

**Comment by samveen** [comment]
@n4ru I'll start with easiest first.

- The date 2019/10/03 is in standard reversed format of `YYYY/MM/DD` (good for listing dates that work well with natural sort without any manipulation :smile:).
- I agree that an `unlock` patch is really a waste of your time and effort.
- I did 2 sets of patching. First set was version 2.75: this obviously did not match the patched-bios/X230.rom, and told me that I had done something wrong. Then I discovered that I needed to use 2.77 as base for patching. The result was a perfect match.
- I'll create a `Work-In-Progress` PR so that it can be reviewed.
- Lastly, can you add notes of any investigation you did about EC patching to tie in with ivyrain? (My aim there is that I want to figure out if it's possible to do patched 2.77 bios + fully functional x220 keyboard).
- I am not paranoid, the big actors are really out to get us all :sweat_smile:

**Comment by n4ru** [comment]
EC patching is covered in both the FAQ and the main README. If you patch your EC first, everything will work fine since 1vyrain does not touch the EC at all.

**Comment by samveen** [comment]
@n4ru One concern is (and I didn't see any info about it) that will the BIOS downgrade affect the EC firmware too, given that BIOS and EC are usually packaged together? The downgrade guide mention BIOS version 2.60. As per the [release file for BIOS 2.77](https://download.lenovo.com/pccbbs/mobiles/g2uj33us.txt), the EC version in the package is 1.13: 
```
  2.60  (G2UJ17US)  2.60  (G2ETA0WW)       1.13  (G2HT34WW)    01    2014/03/14
```

Any information on this?

**Comment by n4ru** [comment]
pgera and ch1p's contributions in that issue and another one were actually the original inspiration for 1vyrain. EC is flashed and handled very differently hence why they're separate projects and why I haven't tried merging in the EC changes into mine.

**Comment by tlaurion** [comment]
> I did some minor investigating recently, but after several bricks, gave up on building an "unlock" patch for the 1vyrain patched-bioses. Because IFD actually leaves BIOS unlocked and the Lenovo BIOS locks itself from writing on boot, it should theoretically be possible to remove the BIOS write lock as a patch itself and be able to update without downgrading past the first time.

@n4ru : that would be really welcome in the goal of flashing a [whole 12mb flash rom](https://github.com/osresearch/heads/pull/703). Even more for [t4xx boards](https://doc.coreboot.org/mainboard/lenovo/t4xx_series.html), which would not require to disassemble completely the laptop to access SPIs for initial flash (considering x230-flash or skull would not be needed in that case to flash Heads.

If you have any traces of your attempts, I would gladly help unlocking ifd so that we can fully flash the complete 12Mb rom as asked in #2 .

**Comment by n4ru** [comment]
> > I did some minor investigating recently, but after several bricks, gave up on building an "unlock" patch for the 1vyrain patched-bioses. Because IFD actually leaves BIOS unlocked and the Lenovo BIOS locks itself from writing on boot, it should theoretically be possible to remove the BIOS write lock as a patch itself and be able to update without downgrading past the first time.
> 
> @n4ru : that would be really welcome in the goal of flashing a [whole 12mb flash rom](https://github.com/osresearch/heads/pull/703). Even more for t4xx boards, which would then not [require complete disassembly of the laptop](https://doc.coreboot.org/mainboard/lenovo/t4xx_series.html) to access SPIs for initial flashing (considering x230-flash or skull will soon not be needed anymore to flash Heads, nor ifdfake call being needed as per this [PR](https://github.com/osresearch/heads/pull/703).)
> 
> If you have any traces of your past attempts to unlock IFD, I would gladly try to give a hand so that we can fully flash the complete 12Mb rom as asked in #2 for OEM scenarios (batch reprogramming), and then even implement [forward sealing](https://github.com/osresearch/heads/issues/523).

The unlock would only be the `bios` region, so it wouldn't help you there.
