### ISSUE TITLE
How about W541?

### ISSUE THREAD

**Issue by ccieliu** [n4ru/1vyrain#36]
Hi Team,

Your project so amazing to creak thinkpad bios.
But how about W541? i see the W530 in list, but how about the W541?
I replace my Thinkpad541 screen, but cannot change brightness.
I think that;s the bios whitelist issue.
If I can fix the issue use your project?

Bruce Lau.

**Comment by digmorepaka** [comment]
If memory serves me right, we explored the possibility of using this on haswell series but full unlock wasn't achieved. You can still modify with and external flash. I don't believe any xx40 ThinkPad has screen whitelist except X240, but it is possible due to it being a sort of refreshed. If brightness control is broken on windows but works on *nix systems, it's the whitelist. On the discord linked in the 1vyrain documentation there is a few people who could find the patch.

**Comment by ccieliu** [comment]
> If memory serves me right, we explored the possibility of using this on haswell series but full unlock wasn't achieved. You can still modify with and external flash. I don't believe any xx40 ThinkPad has screen whitelist except X240, but it is possible due to it being a sort of refreshed. If brightness control is broken on windows but works on *nix systems, it's the whitelist. On the discord linked in the 1vyrain documentation there is a few people who could find the patch.

Hi digmorepaka,

Thanks for your reply. But please let me know, 
what's meaning "but it is possible due to it being a sort of refreshed"?
So sorry i am not native english speaker.


Bruce lau

**Comment by digmorepaka** [comment]
I mean it as, W541 was a later revision of W540. And changes such as that whitelist could have been made. Refresh is meant as in new generation with very minor changes to it's previous model.
