### ISSUE TITLE
Flashrom argument regression

### ISSUE THREAD

**Issue by pgera** [n4ru/1vyrain#51]
I'm hitting what appears to be flashrom argument regression. The latest version errors out with a size mismatch error. 

Details: T530
Error: size (4202496 B) doesn't match the flash chip's size (12582912 B)

Looks like it's not selecting the bios region.

**Comment by digmorepaka** [comment]
Flashrom checks filesize regardless of region. If you're flashing a 4M region of an 8M chip it will still require you to have an 8M image, since the `bios` region is 4M and at the absolute bottom of the flashmap we pad it by `[chipsize] - 4M`. 

It would be helpful if you could replicate this issue, exit out of the script, and post the output of the following commands:

`echo $flashsize`
`echo $padding`

**Comment by pgera** [comment]
Looks like the iso that I downloaded was stale. It didn't have this fix:

dd if=/dev/zero of=/root/bios/pad bs=1 count=$padding
dd if=/dev/zero of=/root/bios/pad bs=1K count=$padding

I think it should work fine now with the current iso.

**Comment by digmorepaka** [comment]
Ah.
