### ISSUE TITLE
Clarify used binaries

### ISSUE THREAD

**Issue by Naheel-Azawy** [n4ru/1vyrain#99]
Hello,

First I'd like to thank you and everyone who have contributed to this work; this is absolutely wonderful.

My concern is regarding the binaries I found here. I'm not sure if it's just that I haven't searched enough or if these binaries are provided without any source.
I'd appreciate it if you can provide the sources or any further clarification for the following:

- 1vyrain/tools/patcher/patcher
- patched-bioses/*.rom
- IVprep/BIOS/WinFlash64.exe
- IVprep/BIOS/*.FL1; are these straight from Lenovo's website?
- Any other binaries if I have missed any?

Thanks again

**Comment by digmorepaka** [comment]
1vyrain/tools/patcher/patcher UEFIPatch 0.27.0 - not used since rev3

patched-bioses/*.rom https://github.com/n4ru/patched-bioses https://github.com/digmorepaka/thinkpad-firmware-patches

IVprep/BIOS/WinFlash64.exe Lenovo update package, I don't think it's the one from xx30 because those crash on 64bit windows 10 in some  cases

IVprep/BIOS/*.FL1 straight from lenovo's website

and one last one that's not properly documented is a version of flashrom. [iso]/root/flashrom/flashrom is flashrom v1.1-rc1-131-g3eae695 with one of the 128MBit macronix chips removed

**Comment by Naheel-Azawy** [comment]
Thank you @digmorepaka. I guess let's keep this open until it gets documented.
People who are paranoid enough to mess around with their bios's fear binaries, at least I do.

**Comment by digmorepaka** [comment]
k

**Comment by n4ru** [comment]
The first question of the longform FAQ has a link to self-build without relying on any precompiled binaries.

**Comment by Naheel-Azawy** [comment]
Sweet, thank you @n4ru
